// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGfEdOm1Yth63V3K0_P0WDHo-XKAJuJ-0',
    appId: '1:637982491647:web:a55e6a0fc78fc4a891ddca',
    messagingSenderId: '637982491647',
    projectId: 'pharaoh-quest',
    authDomain: 'pharaoh-quest.firebaseapp.com',
    storageBucket: 'pharaoh-quest.appspot.com',
    measurementId: 'G-BZSV4ELVL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpjI9mlan2Hg-HXtIqOrLaFLBDy-YLuNg',
    appId: '1:637982491647:android:11e886a3a7ff09d091ddca',
    messagingSenderId: '637982491647',
    projectId: 'pharaoh-quest',
    storageBucket: 'pharaoh-quest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeiEUZuzsEq1p7KIJWqG3IZBkJsKhnZYQ',
    appId: '1:637982491647:ios:477cac08d761772391ddca',
    messagingSenderId: '637982491647',
    projectId: 'pharaoh-quest',
    storageBucket: 'pharaoh-quest.appspot.com',
    iosClientId: '637982491647-009doo0ji8u8ca1ffcopnpe0si55q1dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharaohQuset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeiEUZuzsEq1p7KIJWqG3IZBkJsKhnZYQ',
    appId: '1:637982491647:ios:477cac08d761772391ddca',
    messagingSenderId: '637982491647',
    projectId: 'pharaoh-quest',
    storageBucket: 'pharaoh-quest.appspot.com',
    iosClientId: '637982491647-009doo0ji8u8ca1ffcopnpe0si55q1dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharaohQuset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGfEdOm1Yth63V3K0_P0WDHo-XKAJuJ-0',
    appId: '1:637982491647:web:bf6ae6d718e6d2d691ddca',
    messagingSenderId: '637982491647',
    projectId: 'pharaoh-quest',
    authDomain: 'pharaoh-quest.firebaseapp.com',
    storageBucket: 'pharaoh-quest.appspot.com',
    measurementId: 'G-BY0L9B9237',
  );

}